version: 2
updates:
  - package-ecosystem: "npm"
    directories:
      - "/"
      - "/packages/sprinkle"
    schedule:
      interval: "weekly"
    groups:
      dependencies:
        patterns:
          - "*"
    reviewers:
      - "Oleksii Dubok"
    open-pull-requests-limit: 5

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      actions:
        patterns:
          - "*"
    reviewers:
      - "Oleksii Dubok"